version: "3"
services:
  mysql-db:
    image: mysql
    container_name: todo-mysql-db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=MANO
      - MYSQL_PASSWORD=MANO
  todo-service:
    build: .
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILE}"

    depends_on:
      - mysql-db